### ISSUE TITLE
more control over hybrid functionals

### ISSUE THREAD

**Issue by bernstei** [SPARC-X/SPARC#125]
It might be useful to add more hybrid functionals, or maybe just direct control over things like fraction of exact exchange, fraction of PBE correlation, etc, which can define at least some of the existing hybrid functionals.

**Comment by YaphetS-jx** [comment]
Thanks for your feedback! We will add the control of fraction of exact exchange in next update.

**Comment by YaphetS-jx** [comment]
We just add the `EXX_FRAC` option to control the fraction of exact exchange. You can check details in the docs.

**Comment by bernstei** [comment]
Great, thanks.

BTW, is there any way to generate a manual that isn't a PDF?  Searching that seems to be at least somewhat broken - I can't search for the parts of the keywords that include an underscore, for example.

**Comment by ajmedford** [comment]
The source code for the manual is available in .tex files that are in principle searchable: https://github.com/SPARC-X/SPARC/tree/master/doc/.LaTeX

In principle it should be able to use [pandoc](https://pandoc.org/) to convert to other output formats as desired.

**Comment by bernstei** [comment]
Thanks.  Web docs, ideally automatically generated by a github action, maybe on github.io, would be really helpful as well.

**Comment by ajmedford** [comment]
Yes, we considered this at some point but decided to focus our efforts on adding features in the beginning. We may revisit the documentation at some point in the future. Thanks for the suggestion.

**Comment by phanish-suryanarayana** [comment]
@ajmedford I think we should fix this issue of the pdf not being searchable, particularly for keywords that include an underscore, which is nearly every keyword. I am not able to identify why this is happening, could you look into it? Thanks!

**Comment by ajmedford** [comment]
@phanish-suryanarayana it seems that this is due to the underlying search engine of the browser and most .pdf readers which treat underscores as a special character. @bernstei - I did figure out that you can search by just using a space instead of an underscore, which should be a decent work-around. I think the only robust fix is to re-work the documentation so that it renders through a searchable system like [read the docs](https://readthedocs.org/) or Github pages. That is feasible, but will require some effort, so I'm not sure it's worth it at this point (this would be potentially be a good thing to wrap into the re-write of the Python API).

**Comment by bernstei** [comment]
Might this fix the issue with the latex PDF output?

https://latex.org/forum/viewtopic.php?t=8891

**Comment by ajmedford** [comment]
@bernstei - Nice find! It is certainly worth a try.

@phanish-suryanarayana @xuqimen  - It seems like just adding `\usepackage[T1]{fontenc}` to the preamble will likely fix the issue.

**Comment by bernstei** [comment]
I do still suggest eventually adding more documentation formats, in particular something more browser-text-like than pdf, e.g. using pandoc.

**Comment by xuqimen** [comment]
@ajmedford @bernstei Yes, I just tried adding `\usepackage[T1]{fontenc}` and it seems to be working. We'll update it soon.
