### ISSUE TITLE
Magnetization calculation in cyclix

### ISSUE THREAD

**Issue by sharm608** [SPARC-X/SPARC#210]
Hi,

I have a few questions on spin polarized calculations in Cyclix:

1. I was going through the Cyclix code and could not find a routine for calculating atomic magnetization but the code prints magnetization values. I am wondering whether those values are correct. 
2. The .dens flies generated by the Cyclix code looks like .cube file. I used Vesta to plot isosurfaces but it did not plot anything. I looked at the .dens file and it has 0 as a value in voxels.  Usual .cube files are in cartesian coordinates. Is the density printed in this file by the code in cylindrical coordinate system?
3. Does DCP boundary conditions allow for non-zero twist?
Many thanks,
Shivam

**Comment by shashikant193** [comment]
Hi Shivam,

Please see my responses below:

1. SPARC supports spin-polarized and spin-orbit coupling calculations for Cyclix boundary conditions. The code prints the net magnetization for the whole system. While atomic magnetization isn't currently supported, you can calculate it by partitioning the electron density using Bader analysis or other schemes.

2. The .dens file data is in cylindrical coordinates aligned with the FD grid specified in the .inpt file. It cannot be directly plotted in VESTA since the grids are not Cartesian. 

3. Non-zero twist is supported for 'DCH' boundary conditions. For 'DCP', the twist is always zero as the axial direction is periodic.

Regards,
Shashikant Kumar

**Comment by sharm608** [comment]
Hi Shashikant, 

Thanks for clarifications. I appreciate it.

Regards,
Shivam

**Comment by sharm608** [comment]
Hi,

I have a follow up question. Is it possible to apply external twist in the rectangular unit cell of the nanotube and use DCH boundary condition instead of DCP? For example in this case https://github.com/SPARC-X/SPARC/tree/master/tests/HfSe2_cyclix/standard rectangular unit cell is used. Will it be correct to apply external twist to it and change the boundary conditions to DCH?

Many thanks,
Shivam

**Comment by shashikant193** [comment]
Hi Shivam,

Yes, you can apply an external twist to the rectangular unit cell using the TWIST_ANGLE tag and change the boundary condition to DCH.

Many thanks,

**Comment by sharm608** [comment]
Thanks a lot Shashikant for clarification.
